/* File:      js/autocomplete-keyword.js
 * Website:   nestedkeywords.com
 * Webmaster: Barry Hansen, barry@electromagneticsoftware.com
 * Generated on: Thu, 19 Sep 2019 05:20:03 -0700
 * Generated by: keyword-database.php
 */
$( ".autocomplete" ).autocomplete({
source: [ 
    "185th Street", "1900-1999", "1900s", "1910s", "1920s", "1930s", "1960s", "1970s", "Actions", 
    "Adults", "Agents", "Attributes", "Aurora Avenue", "Baseball", "Beaches", "Black and White", 
    "Buildings", "Casual wear", "Children", "Cities", "Clothing", "Commercial Buildings", "Construction", 
    "Dates", "Dogs", "Dress clothes", "Emotions", "Entertainment", "Entities", "Events", "Flags", 
    "Footwear", "Frames", "Genre", "Grocery stores", "Groups", "Hats", "Horses", "Infants", "Journalistic", 
    "Lake Forest Park", "Landforms", "Livestock", "Locations", "Medical devices", "Musical Instruments", 
    "Named Places", "Named Streets", "Neighborhoods", "Neutral", "No Date", "Nonmoving", "Occupations and businesses", 
    "Oceans and sounds", "People", "Pets", "Picnics", "Playing", "Portraits", "Posing", "Print properties", 
    "Proud", "Public", "Retail", "Richmond Beach", "Richmond Beach Baseball Team", "Richmond Highlands", 
    "Ronald Elementary School Teams", "Ronald School", "School buildings", "School photos", "Shoreline", 
    "Social events", "Sporting", "Steel", "Swimwear", "Teaching", "Teams", "Technologies", "Uniforms", 
    "Wood", "Working", 
]
});

